### ISSUE TITLE
No Advanced Lighting OpenGL Mac OSX

### ISSUE THREAD

**Issue by JeffProgrammer** [GarageGames/Torque3D#1172]
Advanced lighting currently does not work on Mac OSX.

It refuses to enable. Have to investigate more.

@eightyeight can you throw the OSX label on here :)

**Comment by galek** [comment]
You corrected script?(where is activation of AL)
Delete Check if(platform==macosx)return;

**Comment by JeffProgrammer** [comment]
didn't know there was script blocking it, will check soon, thanks :)

**Comment by JeffProgrammer** [comment]
@galek where is the script that is causing this? I can't seem to find it.

**Comment by galek** [comment]
@JeffProgrammer 
in Templates\Full\game\core\scripts\client\lighting\advanced\init.cs

function onActivateAdvancedLM()
{
   // Don't allow the offscreen target on OSX.
   if ( $platform $= "macos" )
      return;
                  
   // On the Xbox360 we know what will be enabled so don't do any trickery to
   // disable MSAA
   if ( $platform $= "xenon" )
      return;
      
   // Enable the offscreen target so that AL will work
   // with MSAA back buffers and for HDR rendering.   
   AL_FormatToken.enable();
}

**Comment by JeffProgrammer** [comment]
i removed the mac OSX check, and it still refuses to enable advanced lighting.

**Comment by JeffProgrammer** [comment]
progress! good and bad.
Good:
So, funny enough, there's some old legacy GL checking that was making advanced fail. managed to solve that: https://github.com/JeffProgrammer/Torque3D/commit/b0d0a380d52c0cf19218f183821586c3280e1913

Bad: advanced lighting doesn't quite work....it renders geometry black :/
