### ISSUE TITLE
Projects from 3.6 do not work with 3.7 executable

### ISSUE THREAD

**Issue by eightyeight** [GarageGames/Torque3D#1195]
Everything works fine until a mission finishes loading, whereupon this error happens:

![notinited](https://cloud.githubusercontent.com/assets/904269/6197584/0e402ef2-b43c-11e4-810d-5b6fdc0d0e20.png)

Hilariously, I can't resize the error dialog to see the exact line, and there are four separate `Not init'ed` errors in the source [here](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/materials/matInstance.cpp#L519-L556), which I recommend we differentiate slightly.

I see a bunch of lines like this in the console:

    CustomMaterial(WaterMat) bind sampler[$refractBuff] and is not present on ShaderData(WaterShader)
    ShaderData(ParticlesShaderData): samplerNames[0] = "$" are diferent to sampler in shader: $diffuseMap : register(S0)
    ShaderData(ParticlesShaderData) sampler $diffuseMap not defined
    ShaderData(OffscreenParticleCompositeShaderData): samplerNames[0] = "$" are diferent to sampler in shader: $colorSource : register(S0)
    ShaderData(OffscreenParticleCompositeShaderData) sampler $colorSource not defined

And the last entry is

    CustomMaterial - AL_VectorLightMaterial(1628) - Failed to load texture #ssaoMask$ssaoMask
    GFXD3D9Shader::_compileShader - Error compiling shader: E_FAIL: An undetermined error occurred (80004005)
       C:/code/Torque3D-ProjectManager/bin/win32/My Projects/361 Test/game/shaders/common/lighting/advanced/vectorLightP.hlsl(70,27): error X3004: undeclared identifier 'prepassUncondition'
    Failed to initialize material 'AL_VectorLightMaterial'

It's up to the OpenGL peeps to decide if we want to fix this, though for what it's worth I think we really should put a priority on keeping compatibility with old projects.

**Comment by eightyeight** [comment]
@LuisAntonRebollo and @Azaezel it would be great to get your opinion on this.

**Comment by Azaezel** [comment]
The first chunk at least is due to a lack of entries in the relevant game\core\scripts\client\ shader mapping definitions. For particles, that would be https://github.com/GarageGames/Torque3D/blob/development/Templates/Full/game/core/scripts/client/shaders.cs#L36 corresponding to https://github.com/GarageGames/Torque3D/blob/master/Templates/Full/game/shaders/common/particlesP.hlsl#L50 in a case sensitive manner for instance. Not really any way to rule that out, given it's a flat out requirement for the GL side of things as written.

Would need to root around a bit on the second, fatal chunk for where that ends coming from.

**Comment by eightyeight** [comment]
I guess a good idea might be to see if we can identify a minimal subset of changes so we can guide people through the port.

**Comment by LuisAntonRebollo** [comment]
@eightyeight, can you retest plz?

If you find some problem tellme how i can reproduce :P

**Comment by eightyeight** [comment]
Oh wow, everything appears to work fine. What did you do? Thanks! :grinning:
