### ISSUE TITLE
[Request] SMAA

### ISSUE THREAD

**Issue by razvanab** [GarageGames/Torque3D#1359]
I would like to see smaa support in Torque 3d.
http://www.iryoku.com/smaa/

**Comment by eightyeight** [comment]
Me too.

**Comment by rextimmy** [comment]
@eightyeight 

I got SMAA working in DM a few months back, i'm happy to pass on some of this. I didn't get it fully working under GL though and since we don't use GL in DM i didn't bother chasing it down any further. It works perfectly with D3D9 though. We also use a different options menu so the whole code is kind of integrated to support that but i could break it down and let someone else finish it off. Much nicer results compared to FXAA

**Comment by eightyeight** [comment]
That'd be awesome! Maybe making a forum post with a GitHub branch for people to play with would be a good idea. Also, @razvanab we're trying to enforce the use of GitHub just for actionable bug reports or PRs with new features, rather than feature requests. The [forums](http://forums.torque3d.org/) would be a better place for this!
