### ISSUE TITLE
Console Docstrings returning random strings

### ISSUE THREAD

**Issue by Alex-doc** [GarageGames/Torque3D#1546]
Apparently, the console functions can lead to unpredictable strings when they print
the docstring or an invalid function is called(only tested on them, but there could be more cases).
Reference image:
http://imgur.com/I8fz0L9

**Comment by dottools** [comment]
I guess I don't see the problem, what is it you're expecting differently?

**Comment by Alex-doc** [comment]
the problem is the variable gets assigned a (apparently) random string.
Example of output on my game, based on 3.5 (console left untouched since)
http://imgur.com/JmNFZbn

As you can see, $a is empty as it should, while in the new version (previous post link) it becomes "Val" and then "s"

**Comment by dottools** [comment]
I think that happens is because TorqueScript VM has its own registers and treats them the same way a regular processor would regarding parameters, working, and return value registers.

Case in point what you're doing is the TS equivalent of this C code:
```C
// source1.c
void whatever(int num)
{
    num += 2;
    num -= 8;
}

// source2.c
extern int whatever(int num);

int main(int argc, char *argv[])
{
    printf("result = %d\n", whatever(15));
    return 0;
}
```

The output would be `result = 15` on ARM systems as R0 is used both as first function argument and return value. Not sure about x86, but none the less TorqueScript VM uses registers in similar fashion from what I recall. So anyway my point being when using console exposed functions incorrectly you should expect weird things to happen.

And although would be nice for TS to generate warnings when using functions incorrectly it would mean adding even more overhead to an already slow executing script engine.

**Comment by Alex-doc** [comment]
thanks for the clarification, I close this issue!
