### ISSUE TITLE
The fps is very low

### ISSUE THREAD

**Issue by huhorler** [GarageGames/Torque3D#1792]
```
  If there is an other window in the rect of the game window, the fps is very low
```

**Comment by John3** [comment]
This is a normal behavior when you "sends" torque3d to the background. You can disable this behavior, see this link: http://wiki.torque3d.org/scripter:controlling-framerate-when-the-window-is-unfocused

**Comment by huhorler** [comment]
I have set $Platform::backgroundSleepTime to 1 and the problem is still.I will sends this to the forum.

**Comment by Bloodknight** [comment]
I suspect that if you want the game to run at 100% while not the foreground task then you will have to do some tinkering at the Operating System level as it automatically reduces the CPU and GPU task time of all applications unless specifically ordered otherwise.

This should not be considered a bug or an issue given that you appear to want very custom behaviour.

**Comment by Areloch** [comment]
Yeah, this sounds like some customized behavior that falls outside of the regular focus/window timing. The forums will be your best bet in trying to figure out how to customize this to your needs. For now, I'll close this issue.
