### ISSUE TITLE
Nav mesh in editor does not stay hidden

### ISSUE THREAD

**Issue by Duion** [GarageGames/Torque3D#1864]
When you have a nav mesh object in your mission simgroup and you hide it, it will hide, but when you exit the editor and open the editor again it is no longer hidden but visible, even thought it is still marked as hidden. Same is when you hide it and quit the game and then re open the level in editor, it will be visible again.
This is only for the nav mesh, all other objects work fine with hiding etc I think.

**Comment by John3** [comment]
for me is working ok, can you confirm again this issue? 

How you hided the nav mesh? like this

![image](https://cloud.githubusercontent.com/assets/1057449/21209931/fdb2abc6-c23c-11e6-9246-0fb7d9830917.png)


You can either test again with your compiled version or try with my release from here https://github.com/John3/Torque3D_Unofficial/releases/tag/v1.0.15 just download the exe and copy to your project.

**Comment by Duion** [comment]
Hm did not see that option, I hid it in the scene tree, where you normally hide all objects as well.
So that seems to be a global option in the editor if the mesh should be visible or not, so maybe that overrides the set hidden option in the scene tree.

**Comment by John3** [comment]
hmmmm so you are using this option, from the properties? 

![image](https://cloud.githubusercontent.com/assets/1057449/21247285/01201c0a-c2f4-11e6-8a79-1ab35270415b.png)

This option TMK is not for the navmesh, you need to use the the provided options from navigation editor in the first pic.

**Comment by Duion** [comment]
Yes, it was just a bit confusing since normally you always use that option, it works for all objects, but apparently nav mesh is special.
So close this issue now or do others have problems with that as well? I had the navMesh using a lot of performance so I tried to hide it in the mission group.

**Comment by John3** [comment]
`So close this issue now or do others have problems with that as well?` I think is safe to close, because the hidden options is for other kind of objects. Maybe we can remove that option.

`I had the navMesh using a lot of performance so I tried to hide it in the mission group.` What kind of performance issue? You need to disable the intermediates and rebuild in the background. With the intermediates disabled will help with this performance issue. (I have a few tuto videos about this if you want to see it)

![image](https://cloud.githubusercontent.com/assets/1057449/21248256/67d57664-c2fb-11e6-907e-defba7340a14.png)

If the intermediates is not the problem, you need tune the tiles size according your level. Ex, if you have the tile size too small and the navmesh is too big... well you know what I mean.

**Comment by Duion** [comment]
I have a navMesh with 1x1 km size with tile size 10, that goes on the performance quite a bit.

**Comment by crabmusket** [comment]
Yeah, rendering that in debug mode won't be very fast! :( Making the editing hidden checkbox work properly would probably be the ideal solution.

**Comment by Duion** [comment]
The hidden checkbox works it can just be confused with the regular hidden feature in the mission tree.
Or what did you mean?

**Comment by crabmusket** [comment]
I meant the regular one. Both should work!

**Comment by Duion** [comment]
Yes, it works for when you activate it, but it resets when restarting the editor, probably because the value gets overwritten by the other checkbox.
