### ISSUE TITLE
PR #2056 breaks compilation if TORQUE_AFX is unchecked

### ISSUE THREAD

**Issue by chaigler** [GarageGames/Torque3D#2115]
#2056 merged ArcaneFX into the engine and added the TORQUE_AFX option to the CMAKE build file. This PR includes several ArcaneFX headers throughout the engine which causes linker errors (and prevents compilation) if TORQUE_AFX is unchecked in CMAKE.

I'm assuming these includes need to be wrapped in an #ifdef similar to TORQUE_HIFI or TORQUE_EXTENDED_MOVE.

**Comment by Bloodknight** [comment]
I could see why this would be difficult if you don't use AFX, if you enter at the wrong point it's a spiralling rabbit hole.

As for the old part, yes it is, and integration imo was needed sooner rather than later since it might be even more difficult to integrate later on when other changes take place. 

As far as documentation I believe this should be integrated into the Torque3d wiki area along with other documentation, I also hear on the grapevine that documentation is being overhauled at some point probably as part of the 4.0 update. This gives another point of entry to the FX documentation.

**Comment by chaigler** [comment]
@Bloodknight Thanks for the extra info! I see you're working on ifdef'ing everything (good luck!) in which case I'll have no issue with this being merged in. Hopefully whatever docs exist for AFX can be added to the wiki at some point.
