### ISSUE TITLE
CMake not creating relative paths for visual studio 2014

### ISSUE THREAD

**Issue by velteyn** [GarageGames/Torque3D#2218]
Hello, I was able to compile the project correctly using Cmake 3.4.0 and Visual Studio 2014, but I could not find the option to make relative paths.. I noticed that it made only absolutes...

I think this is a bug :(

**Comment by dottools** [comment]
It is not possible for relative paths in CMake anymore as the CMake devs removed relative path support since v3.4. They did this because their generated Makefiles never could use relative paths and they got tired of making sure non-Makefile generated files work properly with `CMAKE_USE_RELATIVE_PATHS` option and thus stopped supporting it for other toolchains like Visual Studio. CMake devs are heavily Makefile biased, hence why Visual Studio generated projects are always such as mess with things that only Makefile projects really should have.

**Comment by chaigler** [comment]
@velteyn Consider closing this one unless you have some additional info. dottools is correct - CMake hasn't supported relative paths in quite a while.

**Comment by velteyn** [comment]
Im very sorry to hear  this but .. _c'est la vie_
